name: Continuous integration

on: 
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        
        strategy:
          matrix:
            node-version: [16.x, 18.x]

        steps:
          - name: Checkout to new branch
            uses: actions/checkout@v3

          - name: Installing Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'

          - name: Installing packages from the package-lock.json file
            run: npm ci

          - name: Building
            run: npm run build

          - name: Running tests
            run: npm test
